apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nuage-identity.fullname" . }}-secrets
  labels:
    {{- include "nuage-identity.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-password: {{ .Values.secrets.databasePassword | default "CHANGE_ME" | quote }}
  redis-password: {{ .Values.secrets.redisPassword | default "" | quote }}
  encryption-key: {{ .Values.secrets.encryptionKey | default "CHANGE_ME_IN_PRODUCTION_32_BYTES_KEY" | quote }}

